### PR TITLE
Refresh token after expire

### LINKED ISSUE #33: Invalid Credentials (refresh token not working)
I thought this issue was only happen in this repo but also happens in nao package i described it here https://github.com/nao-pon/flysystem-google-drive/issues/99

When i uploading for two hours, i mean i pushed 10 jobs in laravel to upload some files in different times, the first hour is ok and after that i will get : 

```
{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "authError",
    "message": "Invalid Credentials",
    "locationType": "header",
    "location": "Authorization"
   }
  ],
  "code": 401,
  "message": "Invalid Credentials"
 }
}
```

I did exactly what was said in [this article ](https://medium.com/@dennissmink/laravel-backup-database-to-your-google-drive-f4728a2b74bd), i checked the "auto refresh token when expired" but somehow the token will expire after an hour, should i do extra work to refresh the access token ?

### PR DESCRIPTION
**Pull request by erikn69**
Closes #33

### CODE REVIEW

**Comment by foremtehan** [comment]
any plan to release new PRs?

**Comment by erikn69** [comment]
I can't answer that, @masbug  has the super power 🚀

**Comment by sr2ds** [comment]
Hello everyone, thanks for fix this. 

Has some way to force to expire token programmatically?
If yes, how to? Maybe we also can setup one specific test to ensure this situation.

```php
 public function testRefreshTokenAfterExpires()
{
        $adapter = $this->adapter();
        $adapter->logout();
        // assert with error 

        $adapter->refreshToken();
        // assert with success
}
```

**Comment by erikn69** [comment]
> Has some way to force to expire token programmatically?

why?

**Comment by sr2ds** [comment]
> > Has some way to force to expire token programmatically?
> 
> why?

I need make tests in my application and I don't know how to expire token to test, you know?

**Comment by erikn69** [comment]
https://googleapis.github.io/google-api-php-client/main/Google_Client.html
[revokeToken](https://googleapis.github.io/google-api-php-client/main/Google_Client.html#method_revokeToken)

**Comment by sr2ds** [comment]
> https://googleapis.github.io/google-api-php-client/main/Google_Client.html [revokeToken](https://googleapis.github.io/google-api-php-client/main/Google_Client.html#method_revokeToken)

Thanks!

**Pull request merged**
