### PR TITLE
Support FlySystem ^3.0

### PR DESCRIPTION
**Pull request by erikn69**
[flysystem 3.0.0](https://github.com/thephpleague/flysystem/releases/tag/3.0.0) released

Tested V2 and V3
```batch
Runtime:       PHP 8.0.13
Configuration: google_flysystem/phpunit.xml.dist

...................................................               51 / 51 (100%)

Time: 02:02.207, Memory: 10.00 MB

OK ( 51 tests, 80 assertions)
```

### CODE REVIEW

**Comment by masbug** [comment]
Thank you!

**Comment by erikn69** [comment]
@masbug Release for packagist please 👍

**Comment by PaolaRuby** [comment]
@masbug please release this on **2.X**

**Comment by masbug** [comment]
Done.

**Pull request merged**
