### PR TITLE
Fix Countable error on php 8.1 in laravel 9

### PR DESCRIPTION
**Pull request by coendr**
Error message:
`count(): Argument #1 ($value) must be of type Countable|array, null given`

### CODE REVIEW

**Comment by parallels999** [comment]
Closes #91

**Comment by robindirksen1** [comment]
@masbug any update on this PR?

**Comment by parallels999** [comment]
Better https://github.com/masbug/flysystem-google-drive-ext/pull/101

**Comment by masbug** [comment]
Thanks! Superseded by #101.

**Pull request closed without merging**
