### PR TITLE
Add support for team drives

### PR DESCRIPTION
**Pull request by Deltachaos**
Inspired by https://github.com/nao-pon/flysystem-google-drive i have added support for team drives in this driver.

### CODE REVIEW

**Comment by GerardBalaoro** [comment]
@Deltachaos some checks are failing, can you take a look and fix them maybe then this will get merged. I'd do it myself but I don't have write access.

**Comment by Deltachaos** [comment]
@GerardBalaoro the checks only relate to replace `list(..., ...)` with `[..., ...]` which is not supported by the PHP version constraint in the composer.json of the project. Therefore the check is wrong.

**Comment by Deltachaos** [comment]
@masbug is there any chance this getting merged?

**Comment by masbug** [comment]
Sorry for waiting so long. I was swamped with other projects and couldn't test this. 
Thank you for writing the support for team drives!

**Pull request merged**
