### PR TITLE
Add support for Guzzle 7, drop support for PHP 5

### PR DESCRIPTION
**Pull request by mikemand**
I also cleaned up some spacing issues and upgraded PHPUnit, even though it isn't being used (yet).

### CODE REVIEW

**Comment by masbug** [comment]
Thank you!

**Comment by mikemand** [comment]
Thanks for merging! Any chance you could tag a release?

**Comment by masbug** [comment]
I plan to thoroughly test all the pulls before making a new tag (hopefully the last v1.xx release).
After that I plan to add the adaptations for Flysystem V2.

**Comment by mikemand** [comment]
Ah, ok. Looking forward to Flysystem v2!

**Pull request merged**
