### PR TITLE
PHP 8.0 Support

### PR DESCRIPTION
**Pull request by erikn69**
@masbug tested in php 8.0.2

### CODE REVIEW

**Comment by fredsal** [comment]
@masbug hi?

**Comment by fredsal** [comment]
@masbug still there?

**Comment by masbug** [comment]
@fredsal I almost wasn't. Sorry for the delay.

@erikn69 This was tested against flysystem 2+ as well?

**Comment by erikn69** [comment]
@masbug maybe some breaking changes for  flysystem 2+, so maybe start flysystem-google-drive-ext 2.x?

**Comment by fredsal** [comment]
@masbug hi, so, when will we get the release for php 8 support?

**Comment by masbug** [comment]
Done.

**Pull request merged**
