### PR TITLE
follow shortcut to target

### LINKED ISSUE #96: cannot list directory shortcuts
In My Google Drive I have a number of shortcuts to directories that have been shared with me.
I need to be able to upload files into these shared folders but currently
`Storage::disk('google')->listContents('the-shortcut')` just returns []

I've worked around it by forking the code and adding shortcutDetails to FETCHFIELDS_LIST and adding

```
if ($object->mimeType == self::SHORTCUTMIME) {
    $object->mimeType = $object->shortcutDetails->targetMimeType;
    $id = $object->shortcutDetails->targetId;
}
```
near the top of normaliseObject.
but it feels too easy & I wonder what I might be missing

### PR DESCRIPTION
**Pull request by markymarrow**
fixes #96

### CODE REVIEW

**Comment by fredsal** [comment]
Current branch is 2.x

**Comment by markymarrow** [comment]
I'm still running laravel8 so I need this in the 1.x branch.
What is one supposed to do here?

**Comment by fredsal** [comment]
Ok 👍, but when you upgrade laravel this change is not will be available

**Comment by markymarrow** [comment]
I can see previous commits of 'merge branch 1.x into 2.x' - I had assumed that this would happen occasionally

**Comment by masbug** [comment]
Thanks

**Pull request merged**
