### PR TITLE
[V2] Improved Google Class loading

### PR DESCRIPTION
**Pull request by elzdave**
Updated all Google's dependencies to follow PSR-4 autoloader standard, while still maintaining the old constructor params to avoid breaking change

### CODE REVIEW

**Comment by erikn69** [comment]
~~This PR towards 1.x would have been great, so it could be merged with 2.x~~
did you run tests?

**Comment by elzdave** [comment]
Hmm, I couldn't run the test. But okay, I'll try to get it towards the 1.x branch

**Comment by erikn69** [comment]
Let it open, @masbug must decide

**Comment by elzdave** [comment]
Or I make one to target the 1.x branch too?

**Comment by erikn69** [comment]
```php
Runtime:       PHP 8.0.13
Configuration: phpunit.xml.dist

................................................                  48 / 48 (100%)

Time: 02:30.550, Memory: 10.00 MB

OK ( 48 tests, 77 assertions)
```

**Comment by masbug** [comment]
Thank you!

**Pull request merged**
